name: dh_segment_torch
channels:
  - default
  - pytorch
dependencies:
  - pip=19.3.1
  - setuptools=42.0.2
  - python=3.7
  - pytorch=1.3.1
  - ignite==0.2.1
  - torchvision=0.4.2
  - cudatoolkit=10.1
  - tensorboard=2.0.0
  - pip:
      - sacred==0.8.1
      - pretrainedmodels==0.7.4
      - tensorboardX==1.9

