name: dh_segment_torch
channels:
  - default
  - pytorch
dependencies:
  - pip=19.3.1
  - setuptools=44.0.0
  - python=3.7
  - pytorch=1.4.0
  - torchvision=0.5.0
  - cudatoolkit=10.1
  - tensorboard=2.0.0
  - scikit-image=0.15.0
  - pandas=0.25.3
  - pip:
      - sacred==0.8.1
      - pretrainedmodels==0.7.4
      - opencv-python>=4.0.1
      - git+https://github.com/pytorch/ignite


